version: 2
jobs:
   build:
     working_directory: /go/src/github.com/stitchfix/flotilla-os
     docker:
       - image: circleci/golang:1.8
     steps:
       - checkout
       - run: echo "hello world"