# aws region - relevant for aws related components (sqs,ecs)
aws_default_region: us-east-1

# Database url - relevant for database oriented state managers
database_url: postgresql://flotilla:flotilla@localhost/flotolla?sslmode=disable

#
# Configure which managers and clients to use
#
state_manager: postgres
queue_manager: sqs
cluster_client: ecs
logs_client: cloudwatch

# Log namespace
log:
  namespace: flotilla-os-logs
  retention_days: 30

# Queue namespace
queue:
  namespace: dev-flotilla
